exports.ReportTypes = {
  ranking: 'Ranking',
  historial_usuario: 'HistorialUsuario',
  usuarios: 'Usuarios',
  consolidado_cursos_v2: 'ConsolidadoCursos',
  segmentation: 'SegmentaciónCursos',
  consolidado_temas_v3: 'ConsolidadoCompatibleTemas',
  visitas: 'Visitas',
  reinicios: 'Reinicios',
  evaluaciones_abiertas_v2: 'EvaluacionAbierta',
  temas_no_evaluables_v2: 'Temas no evaluables',
  user_uploads: 'Usuario Uploads',
  checklist_general: 'checklist_general',
  checklist_detallado: 'checklist_detallado',
  videoteca: 'Videoteca',
  vademecum: 'Vademecum',
  diplomas: 'Diplomas',
  avance_curricula: 'avance_curricula',
  "poll-questions": 'Reporte-Encuestas'
}
